### ISSUE TITLE
Add logger

### ISSUE THREAD

**Issue by nikravesh** [HesamKashefi/MicroserviceCQRSAndEventSourcingWIthKafka#2]
Hi Hesam,
I want to add logger into EditMessageController, I get a fork and I'll add that.

thanks.

**Comment by HesamKashefi** [comment]
Hi, that would be nice!

**Comment by nikravesh** [comment]
Hi, Thaks

**Comment by HesamKashefi** [comment]
Where is the pull request? @nikravesh

**Comment by nikravesh** [comment]
I created the pull request.

**Comment by HesamKashefi** [comment]
https://github.com/HesamKashefi/MicroserviceCQRSAndEventSourcingWIthKafka/pull/3

**Comment by HesamKashefi** [comment]
Thanks!
Merged the pull request https://github.com/HesamKashefi/MicroserviceCQRSAndEventSourcingWIthKafka/pull/3
